version: '3.8'

services:
  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: order-management-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - MONGODB_URI=mongodb+srv://Code2cash:cash2code1@cluster0.0eoeraf.mongodb.net/
      - MONGODB_DATABASE=orderManagement
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://frontend:80
      - PORT=8080
      - UPLOAD_DIR=/app/uploads
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - order-management-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: order-management-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8080
      - VITE_APP_NAME=Order Management System
      - VITE_APP_VERSION=1.0.0
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - order-management-network

volumes:
  backend_uploads:
    driver: local

networks:
  order-management-network:
    driver: bridge
