version: '3.8'

services:
  # Backend Service - Development
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: order-management-backend-dev
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - MONGODB_URI=mongodb+srv://Code2cash:cash2code1@cluster0.0eoeraf.mongodb.net/
      - MONGODB_DATABASE=orderManagement
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
      - PORT=8080
      - UPLOAD_DIR=/app/uploads
    volumes:
      - backend_uploads:/app/uploads
      - ./backend/src:/app/src:ro
    networks:
      - order-management-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Service - Development (Hot reload)
  frontend-dev:
    image: node:18-alpine
    container_name: order-management-frontend-dev
    working_dir: /app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8081
      - VITE_APP_NAME=Order Management System
      - VITE_APP_VERSION=1.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - order-management-network

volumes:
  backend_uploads:
    driver: local

networks:
  order-management-network:
    driver: bridge
